결제화면 페이지 구현
jaemisam-a/dangol-sonnim-frontend pull request #79
Opened 2023-02-21 01:50 UTC by NiNinanana

## 수정
- 결제화면 페이지 구현
  - 라디오 버튼 크기, 색 지정

## 참고
- 추후
  - text input에 onchange넣어 값 받기
  - 동의서 전문과 연결
  - 카드 종류 연결
- 노션 태스크: https://www.notion.so/71fed7529fff475eab80f902d12e7305?pvs=4

2023-02-21 05:45 UTC, mynameisjisoo requested changes
1. 결제화면 쿠폰의 체크박스는 선택이 안되게 해야할 것 같아요. 
2. 결제화면 헤더에는 공유하기 버튼이 없습니다.  
3. 피그마에는 아래 전화번호 입력 칸이 있는데 확인 부탁드려요.
4. 필수 입력값 누락 시 구매 버튼이 비활성화 기능은 추후 pr에서 진행하시나요?
5. selectbox에도 border-radious 적용해주세요.
6. 현금영수증 발행 라디오 버튼 클릭 시 테두리가 잡히는데 확인 부탁드립니다.
![image](https://user-images.githubusercontent.com/84840032/220252043-ef378b5f-cb4c-413d-95ab-e0b0af972694.png)

7. input 텍스트필드의 삭제 아이콘이 피그마와 다릅니다.

2023-02-21 05:45 UTC, mynameisjisoo commented on src/customer/components/store/payment/Method.tsx
> +      <div css={methodButtonList}>
결제 수단 버튼 리스트가 피그마보다 왼쪽에 치우친 것 같습니다.

2023-02-21 05:45 UTC, mynameisjisoo commented on src/customer/components/store/payment/MethodButton.tsx
> +  background-color: ${isSelected ? Colors.amber50 : "white"};
아랫줄도 `"white"` 로 쓰거나 이 줄을 `Colors.white`로 통일하는 건 어떨까요?

2023-02-21 07:41 UTC, NiNinanana commented
> 1. 결제화면 쿠폰의 체크박스는 선택이 안되게 해야할 것 같아요.
> 2. 결제화면 헤더에는 공유하기 버튼이 없습니다.
> 3. 피그마에는 아래 전화번호 입력 칸이 있는데 확인 부탁드려요.
> 4. 필수 입력값 누락 시 구매 버튼이 비활성화 기능은 추후 pr에서 진행하시나요?
> 5. selectbox에도 border-radious 적용해주세요.
> 6. 현금영수증 발행 라디오 버튼 클릭 시 테두리가 잡히는데 확인 부탁드립니다.
>    ![image](https://user-images.githubusercontent.com/84840032/220252043-ef378b5f-cb4c-413d-95ab-e0b0af972694.png)
> 7. input 텍스트필드의 삭제 아이콘이 피그마와 다릅니다.

1. 수정했습니다.
2. 수정했습니다.
3. 어떤 전화번호를 말씀하시는 건가요? 현금 영수증 관련은 버튼 누르면 나옵니다!
4. 넵, text input에 onChange 속성을 넣어서 값을 저장할 수 있게 하고 진행할 예정입니다.
5. 수정했습니다.
6. 수정했습니다.
7. 수정했습니다.
8. 수정했습니다.
9. 수정했습니다.

2023-02-21 13:24 UTC, mynameisjisoo reviewed
header 오른쪽 공유하기 버튼이 있던 자리에 cursor도 default로 변경하면 좋을 것 같아요.

2023-02-21 13:24 UTC, mynameisjisoo commented on src/customer/components/common/layout/Header.tsx
> +  width: 28px;
rem 단위로 변경해주세요!

2023-02-21 13:40 UTC, NiNinanana commented
> header 오른쪽 공유하기 버튼이 있던 자리에 cursor도 default로 변경하면 좋을 것 같아요.

수정했습니다!

2023-02-22 00:06 UTC, mynameisjisoo approved these changes
👍 👍 👍

2023-02-22 00:25 UTC, merged